language: java
os:
 - osx
 - linux
dist: trusty
jdk: oraclejdk11

addons:
  apt:
    packages:
      - ant
      - ant-optional
install:
; note that packages is the name of a .pkg maker!
 - if [ $TRAVIS_OS_NAME = osx ]; then brew install ant packages; fi
before_script:
 - "export DISPLAY=:99.0"
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ( sh -e /etc/init.d/xvfb start )& fi
 - sleep 3 # give xvfb some time to start
 
