language: java
os:
 - osx
 - linux
jdk: oraclejdk9

before_install:
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x32"
install:
 - if [ $TRAVIS_OS_NAME = osx ]; then brew install ant; fi
before_script:
 - "export DISPLAY=:99.0"
