language: java
os:
 - osx
 - linux
jdk: oraclejdk9

install:
 - if [ $TRAVIS_OS_NAME = osx ]; then brew install ant; fi
 - if [ $TRAVIS_OS_NAME = linux ]; then export DISPLAY=':99.0'&& Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &; fi 
