language: java
os:
 - osx
 - linux
jdk: oraclejdk11

addons:
  apt:
    packages:
      - ant
      - ant-optional
services:
    - xvfb
before_script:
 - xvfb-run --server-args="-screen 0 1024x768x8"
 
