version: 1.0.{build}
image:
  - macos-catalina
# 2017 is the latest with Inno Setup also installed.
  - Visual Studio 2017
  - Ubuntu2004
branches:
  only:
    - master
skip_tags: true
shallow_clone: true

for:
-
  matrix:
    only:
      - image: macos-catalina
      
  install:
    - echo $SHELL
    - /usr/libexec/java_home -V
    - java --version
    - export JAVA_HOME=`/usr/libexec/java_home -v11.+`
    - java --version
    - ant -version

  build_script:
    - ant test
    - ant -f joverseerRelease/build.xml MacOSInstallerPackages

  artifacts:
    - path: jOverseerRelease/dist/build\joverseer-*.pkg
      name: MacOSInstaller
-
  matrix:
    only:
      - image: Visual Studio 2017

  install:
    - cinst ant
    - curl -L https://downloads.sourceforge.net/project/launch4j/launch4j-3/3.13/launch4j-3.13-win32.zip --output C:\projects\joverseer\launch4j.zip
    - 7z x -oC:\projects\joverseer C:\projects\joverseer\launch4j.zip
  build_script:
    - ant test
    - ant -f joverseerRelease\build.xml windowsInstaller
    - ant -f joverseerRelease\build.xml updatezip

  artifacts:
    - path: jOverseerRelease\dist\Output\joverseer-setup*.exe
      name: windowsInstaller
    - path: jOverseerRelease\dist\latestupdate.zip
      name: latestupdate
    - path: jOverseerRelease\src\feed.xml
      name: feed

-
  matrix:
    only:
      - image: Ubuntu2004

  install:
    - sudo apt -y install ant ant-contrib
  build_script:
    - ant test


